name: Compile secp256k1 native code

on:
  push:
    branches:
    - master

jobs:
  compile:
    name: Compile secp256k1 native code
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

  # TODO: add release job
